[phases.setup]
nixPkgs = ["nodejs_22", "python311Full"]

[phases.install]
cmds = [
  "cd app && npm ci",
  "cd app && python3 -m pip install -r requirements.txt"
]

[start]
cmd = "cd app && npm run start"
