// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fewmybonsxgrhiywbyzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZld215Ym9uc3hncmhpeXdieXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMDI2MTAsImV4cCI6MjA4Njc3ODYxMH0.eQ9SYi01-Uet_VxCx9ytcYIAxFDkIxSb8aU8cf0__Fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});