[phases.setup]
nixPkgs = ["nodejs_22", "python311", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "npm ci",
  "virtualenv -p python3 .venv",
  ".venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "PYTHON_BIN=.venv/bin/python npm run start"
