CREATE TABLE IF NOT EXISTS images (
  id SERIAL PRIMARY KEY,
  image_path TEXT NOT NULL,
  result VARCHAR(50) NOT NULL,
  confidence DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
